name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: 1162934814:AAFwn40stOdbSp6fns77ElU2f5kq53jODDg
        args: The ${{ github.event_name }} event triggered first step.